from __future__ import annotations

import asyncio
import atexit
import inspect
import weakref
from dataclasses import dataclass
from typing import Annotated, Any, Dict, List, Optional, TypedDict

from services.llm.llm_service import LLMService

LANGGRAPH_INSTALL_MESSAGE = (
    "LangGraph chat memory dependencies are unavailable. "
    "Install backend requirements and retry."
)
GENERIC_MODEL_ERROR_MESSAGE = "The model call failed. Please try again."
MAX_HISTORY_MESSAGES_IN_PROMPT = 12
DEFAULT_MAX_CONTEXT_TOKENS = 128_000
MAX_RESPONSE_TOKENS = 4_096
CONTEXT_USAGE_HARD_LIMIT_PERCENTAGE = 95.0
CONTEXT_WINDOW_ERROR_MESSAGE = (
    "Context window is too large. Remove a document, start a new chat, "
    "or use a model with a larger context window."
)


class ModelProviderError(Exception):
    pass


class ContextWindowExceededError(Exception):
    def __init__(self, context_usage: Dict[str, Any]):
        super().__init__(CONTEXT_WINDOW_ERROR_MESSAGE)
        self.context_usage = context_usage


try:
    from langchain_core.messages import AIMessage, BaseMessage, HumanMessage
    from langchain_core.runnables import RunnableConfig

    LANGCHAIN_MESSAGES_IMPORT_ERROR: Optional[ImportError] = None
except ImportError as exc:
    AIMessage = BaseMessage = HumanMessage = RunnableConfig = Any  # type: ignore[assignment]
    LANGCHAIN_MESSAGES_IMPORT_ERROR = exc

try:
    from langgraph.graph import END, START, StateGraph
    from langgraph.graph.message import add_messages

    LANGGRAPH_GRAPH_IMPORT_ERROR: Optional[ImportError] = None
except ImportError as exc:
    END = "__end__"
    START = "__start__"
    StateGraph = None
    LANGGRAPH_GRAPH_IMPORT_ERROR = exc

    def add_messages(existing: List[Any], new: List[Any]) -> List[Any]:
        return [*(existing or []), *(new or [])]


try:
    from langgraph.checkpoint.memory import InMemorySaver as LangGraphInMemorySaver

    LANGGRAPH_MEMORY_IMPORT_ERROR: Optional[ImportError] = None
except ImportError:
    try:
        from langgraph.checkpoint.memory import MemorySaver as LangGraphInMemorySaver

        LANGGRAPH_MEMORY_IMPORT_ERROR = None
    except ImportError as exc:
        LangGraphInMemorySaver = None
        LANGGRAPH_MEMORY_IMPORT_ERROR = exc


@dataclass
class ChatMemoryRequest:
    user_id: str
    chat_session_id: str
    query: str
    model_type: str
    model_id: Optional[str] = None
    deployment: Optional[str] = None
    api_version: Optional[str] = None
    document_context: Optional[str] = None


class ChatState(TypedDict):
    messages: Annotated[List[BaseMessage], add_messages]


class ChatMemoryService:
    """Persist per-user chat turns with LangGraph and build bounded prompts.

    `chat_session_id` is generated by the client, so the persisted LangGraph
    thread also includes `user_id`. Document content is passed as request-time
    context only and is deliberately excluded from stored chat messages.
    """

    def __init__(
        self,
        llm_service: Optional[LLMService] = None,
        checkpointer: Optional[Any] = None,
        use_memory_checkpointer: bool = False,
    ):
        self.llm_service = llm_service or LLMService()
        self._use_memory_checkpointer = use_memory_checkpointer
        self._async_checkpointer_context = None
        self._did_register_atexit_close = False
        self._initialization_lock = asyncio.Lock()
        self._session_locks: weakref.WeakValueDictionary[str, asyncio.Lock] = (
            weakref.WeakValueDictionary()
        )
        self._ensure_langgraph_dependencies(require_in_memory=use_memory_checkpointer)
        self.checkpointer = checkpointer
        self.graph = (
            self._build_graph(checkpointer) if checkpointer is not None else None
        )

    def _ensure_langgraph_dependencies(self, require_in_memory: bool = False) -> None:
        import_errors: List[str] = []

        if LANGCHAIN_MESSAGES_IMPORT_ERROR is not None:
            import_errors.append(
                f"langchain_core.messages: {LANGCHAIN_MESSAGES_IMPORT_ERROR}"
            )
        if LANGGRAPH_GRAPH_IMPORT_ERROR is not None:
            import_errors.append(f"langgraph.graph: {LANGGRAPH_GRAPH_IMPORT_ERROR}")
        if require_in_memory and LANGGRAPH_MEMORY_IMPORT_ERROR is not None:
            import_errors.append(
                f"langgraph.checkpoint.memory: {LANGGRAPH_MEMORY_IMPORT_ERROR}"
            )

        if import_errors:
            details = "; ".join(import_errors)
            raise RuntimeError(f"{LANGGRAPH_INSTALL_MESSAGE} Import errors: {details}")

    def _get_async_postgres_saver_class(self) -> Any:
        from langgraph.checkpoint.postgres.aio import AsyncPostgresSaver

        return AsyncPostgresSaver

    async def _build_checkpointer(self) -> Any:
        if self._use_memory_checkpointer:
            return self._build_in_memory_checkpointer()

        try:
            AsyncPostgresSaver = self._get_async_postgres_saver_class()
        except Exception as exc:
            raise RuntimeError(
                f"Failed to import LangGraph Postgres checkpointer: {exc}"
            ) from exc

        try:
            from models.base import DATABASE_URL

            saver_context = AsyncPostgresSaver.from_conn_string(DATABASE_URL)
            self._async_checkpointer_context = saver_context
            saver = await saver_context.__aenter__()
            self._register_checkpointer_cleanup()
            if hasattr(saver, "setup"):
                setup_result = saver.setup()
                if inspect.isawaitable(setup_result):
                    await setup_result
            return saver
        except Exception as exc:
            await self._close_async_checkpointer_context()
            raise RuntimeError(
                f"Failed to initialize LangGraph Postgres checkpointer: {exc}"
            ) from exc

    def _register_checkpointer_cleanup(self) -> None:
        if self._did_register_atexit_close:
            return
        atexit.register(self._close_checkpointer_context_at_exit)
        self._did_register_atexit_close = True

    def _close_checkpointer_context_at_exit(self) -> None:
        if self._async_checkpointer_context is None:
            return
        try:
            asyncio.run(self._close_async_checkpointer_context())
        except Exception:
            pass

    async def _close_async_checkpointer_context(self) -> None:
        if self._async_checkpointer_context is None:
            return
        try:
            await self._async_checkpointer_context.__aexit__(None, None, None)
        except Exception:
            pass
        finally:
            self._async_checkpointer_context = None

    def _build_in_memory_checkpointer(self) -> Any:
        if LangGraphInMemorySaver is None:
            detail = (
                str(LANGGRAPH_MEMORY_IMPORT_ERROR)
                if LANGGRAPH_MEMORY_IMPORT_ERROR is not None
                else "LangGraph in-memory saver is unavailable."
            )
            raise RuntimeError(
                f"{LANGGRAPH_INSTALL_MESSAGE} Unable to import LangGraph in-memory saver: {detail}"
            ) from LANGGRAPH_MEMORY_IMPORT_ERROR
        return LangGraphInMemorySaver()

    def _build_graph(self, checkpointer: Any) -> Any:
        self._ensure_langgraph_dependencies()

        graph = StateGraph(ChatState)
        graph.add_node("generate", self._generate_response)
        graph.add_edge(START, "generate")
        graph.add_edge("generate", END)
        return graph.compile(checkpointer=checkpointer)

    async def _ensure_graph(self) -> Any:
        if self.graph is not None:
            return self.graph

        async with self._initialization_lock:
            if self.graph is not None:
                return self.graph

            checkpointer = self.checkpointer or await self._build_checkpointer()
            self.checkpointer = checkpointer
            self.graph = self._build_graph(checkpointer)
            return self.graph

    def _get_session_lock(self, chat_session_id: str) -> asyncio.Lock:
        lock = self._session_locks.get(chat_session_id)
        if lock is None:
            lock = asyncio.Lock()
            self._session_locks[chat_session_id] = lock
        return lock

    def _build_thread_id(self, user_id: str, chat_session_id: str) -> str:
        return f"user:{user_id}:chat:{chat_session_id}"

    async def invoke(self, request: ChatMemoryRequest) -> Dict[str, Any]:
        thread_id = self._build_thread_id(request.user_id, request.chat_session_id)
        config = {
            "configurable": {
                "thread_id": thread_id,
                "model_type": request.model_type,
                "model_id": request.model_id,
                "deployment": request.deployment,
                "api_version": request.api_version,
                "document_context": request.document_context,
            }
        }
        lock = self._get_session_lock(thread_id)
        graph = await self._ensure_graph()

        try:
            async with lock:
                starting_state = await graph.aget_state(config)
                state_config = getattr(starting_state, "config", None) or config
                prior_messages = list(starting_state.values.get("messages", []))
                next_messages = [*prior_messages, HumanMessage(content=request.query)]
                result = await self._generate_response(
                    {
                        "messages": next_messages,
                    },
                    config=config,
                )
                ai_messages = result.get("messages", [])
                persisted_config = await graph.aupdate_state(
                    state_config,
                    {
                        "messages": [*next_messages, *ai_messages],
                    },
                    as_node="generate",
                )
                persisted_state = await graph.aget_state(persisted_config)
                response = self._extract_ai_response(
                    persisted_state.values.get("messages", [])
                )
                return {
                    "success": True,
                    "response": response,
                    "chat_session_id": request.chat_session_id,
                    "context_usage": result.get("context_usage"),
                }
        except ContextWindowExceededError as exc:
            return {
                "success": False,
                "response": "",
                "chat_session_id": request.chat_session_id,
                "error": CONTEXT_WINDOW_ERROR_MESSAGE,
                "error_code": "context_window_exceeded",
                "context_usage": exc.context_usage,
            }
        except ModelProviderError:
            return {
                "success": False,
                "response": "",
                "chat_session_id": request.chat_session_id,
                "error": GENERIC_MODEL_ERROR_MESSAGE,
            }

    async def _generate_response(
        self,
        state: ChatState,
        config: Optional[RunnableConfig] = None,
    ) -> Dict[str, Any]:
        configurable = (config or {}).get("configurable", {})
        prompt = self._build_user_prompt(
            messages=state.get("messages", []),
            document_context=configurable.get("document_context"),
        )
        system_message = self._build_system_message(
            has_document_context=bool(configurable.get("document_context"))
        )
        context_usage = self._build_context_usage(
            user_prompt=prompt,
            system_message=system_message,
            messages=state.get("messages", []),
            document_context=configurable.get("document_context"),
            model_type=str(configurable.get("model_type", "")),
            model_id=configurable.get("model_id"),
            deployment=configurable.get("deployment"),
        )
        if self._is_context_window_too_large(context_usage):
            raise ContextWindowExceededError(context_usage)

        try:
            result = await self.llm_service.generate_paragraph(
                user_prompt=prompt,
                model_type=configurable["model_type"],
                model_id=configurable.get("model_id"),
                deployment=configurable.get("deployment"),
                api_version=configurable.get("api_version"),
                max_tokens=MAX_RESPONSE_TOKENS,
                temperature=0.3,
                system_message=system_message,
            )
        except Exception as exc:
            raise ModelProviderError(GENERIC_MODEL_ERROR_MESSAGE) from exc
        if not result.get("success"):
            raise ModelProviderError(
                str(result.get("error", GENERIC_MODEL_ERROR_MESSAGE))
            )

        return {
            "messages": [AIMessage(content=str(result.get("content", "")))],
            "context_usage": context_usage,
        }

    def _build_user_prompt(
        self,
        messages: List[BaseMessage],
        document_context: Optional[str],
    ) -> str:
        history_lines: List[str] = []
        current_query = ""

        included_messages = self._select_messages_for_prompt(messages)

        for index, message in enumerate(included_messages):
            is_last = index == len(included_messages) - 1
            if isinstance(message, HumanMessage):
                if is_last:
                    current_query = str(message.content)
                else:
                    history_lines.append(f"User: {message.content}")
            elif isinstance(message, AIMessage):
                history_lines.append(f"Assistant: {message.content}")

        sections: List[str] = []
        omitted_count = max(0, len(messages) - len(included_messages))
        if omitted_count:
            sections.append(
                f"Earlier conversation omitted from this request: {omitted_count} message(s)."
            )
        if history_lines:
            sections.append("Conversation so far:\n" + "\n".join(history_lines))
        if document_context:
            sections.append(
                "Current document context for this request:\n"
                f"{document_context}\n\n"
                "Use this context when it is relevant. Do not assume it remains available in future turns unless it is provided again."
            )
        sections.append(f"User question: {current_query}")
        return "\n\n".join(sections)

    def _select_messages_for_prompt(
        self, messages: List[BaseMessage]
    ) -> List[BaseMessage]:
        if len(messages) <= MAX_HISTORY_MESSAGES_IN_PROMPT + 1:
            return messages

        current_message = messages[-1:]
        recent_history = messages[-(MAX_HISTORY_MESSAGES_IN_PROMPT + 1) : -1]
        return [*recent_history, *current_message]

    def _build_context_usage(
        self,
        user_prompt: str,
        system_message: str,
        messages: List[BaseMessage],
        document_context: Optional[str],
        model_type: str,
        model_id: Optional[str],
        deployment: Optional[str],
    ) -> Dict[str, Any]:
        included_messages = self._select_messages_for_prompt(messages)
        prompt_tokens = self._estimate_tokens(user_prompt)
        system_tokens = self._estimate_tokens(system_message)
        document_tokens = self._estimate_tokens(document_context or "")
        max_context_tokens = self._estimate_max_context_tokens(
            model_type=model_type,
            model_id=model_id,
            deployment=deployment,
        )
        estimated_tokens = prompt_tokens + system_tokens
        percentage = (
            round((estimated_tokens / max_context_tokens) * 100, 1)
            if max_context_tokens
            else None
        )

        return {
            "estimated_tokens": estimated_tokens,
            "max_context_tokens": max_context_tokens,
            "percentage": percentage,
            "history_message_count": len(messages),
            "included_history_message_count": len(included_messages),
            "omitted_history_message_count": max(
                0, len(messages) - len(included_messages)
            ),
            "document_context_tokens": document_tokens,
            "reserved_response_tokens": MAX_RESPONSE_TOKENS,
            "hard_limit_percentage": CONTEXT_USAGE_HARD_LIMIT_PERCENTAGE,
            "method": "estimated_chars_div_4",
        }

    def _is_context_window_too_large(self, context_usage: Dict[str, Any]) -> bool:
        max_context_tokens = context_usage.get("max_context_tokens")
        estimated_tokens = context_usage.get("estimated_tokens")
        percentage = context_usage.get("percentage")

        if not max_context_tokens or not estimated_tokens:
            return False
        if estimated_tokens + MAX_RESPONSE_TOKENS >= max_context_tokens:
            return True
        return (
            isinstance(percentage, (int, float))
            and percentage >= CONTEXT_USAGE_HARD_LIMIT_PERCENTAGE
        )

    def _estimate_tokens(self, text: str) -> int:
        if not text:
            return 0
        return max(1, (len(text) + 3) // 4)

    def _estimate_max_context_tokens(
        self,
        model_type: str,
        model_id: Optional[str],
        deployment: Optional[str],
    ) -> int:
        model_key = f"{model_id or ''} {deployment or ''}".lower()
        compact_model_key = (
            model_key.replace("-", "")
            .replace("_", "")
            .replace(".", "")
            .replace(" ", "")
        )

        if model_type == "gemini":
            return 1_000_000
        if model_type == "anthropic":
            return 200_000
        if model_type in ("llama", "azure-llama"):
            return 128_000
        if model_type in ("macbook", "vllm"):
            return 32_000
        if "gpt54mini" in compact_model_key or "gpt54nano" in compact_model_key:
            return 400_000
        if "gpt54" in compact_model_key:
            return 1_050_000
        if "gpt5" in compact_model_key:
            return 400_000
        if "gpt-4o" in model_key or "gpt-5" in model_key or "o3" in model_key:
            return 128_000
        return DEFAULT_MAX_CONTEXT_TOKENS

    def _build_system_message(self, has_document_context: bool) -> str:
        if has_document_context:
            return (
                "You are a helpful document assistant for Health Canada support staff. "
                "Answer the user's question using the current document context and remembered conversation. "
                "If the answer is not found in the document context, say so clearly and offer general guidance if possible."
            )
        return (
            "You are a helpful assistant for Health Canada support staff. "
            "Answer questions clearly and concisely using remembered conversation when relevant."
        )

    def _extract_ai_response(self, messages: List[BaseMessage]) -> str:
        for message in reversed(messages):
            if isinstance(message, AIMessage):
                return str(message.content)
        return ""
