"""initial_schema

Revision ID: 03069a8f5e8c
Revises:
Create Date: 2026-03-31 19:11:10.487245

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "03069a8f5e8c"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("accountId", sa.Text(), nullable=False),
        sa.Column("providerId", sa.Text(), nullable=False),
        sa.Column("userId", sa.String(length=36), nullable=False),
        sa.Column("accessToken", sa.Text(), nullable=True),
        sa.Column("refreshToken", sa.Text(), nullable=True),
        sa.Column("idToken", sa.Text(), nullable=True),
        sa.Column("accessTokenExpiresAt", sa.DateTime(), nullable=True),
        sa.Column("refreshTokenExpiresAt", sa.DateTime(), nullable=True),
        sa.Column("scope", sa.Text(), nullable=True),
        sa.Column("password", sa.Text(), nullable=True),
        sa.Column("createdAt", sa.DateTime(), nullable=True),
        sa.Column("updatedAt", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "session",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("expiresAt", sa.DateTime(), nullable=False),
        sa.Column("token", sa.Text(), nullable=False),
        sa.Column("createdAt", sa.DateTime(), nullable=True),
        sa.Column("updatedAt", sa.DateTime(), nullable=True),
        sa.Column("ipAddress", sa.Text(), nullable=True),
        sa.Column("userAgent", sa.Text(), nullable=True),
        sa.Column("userId", sa.String(length=36), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("emailVerified", sa.Boolean(), nullable=True),
        sa.Column("image", sa.Text(), nullable=True),
        sa.Column("createdAt", sa.DateTime(), nullable=True),
        sa.Column("updatedAt", sa.DateTime(), nullable=True),
        sa.Column("role", sa.Text(), nullable=True),
        sa.Column("is_admin", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "verification",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("identifier", sa.Text(), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("expiresAt", sa.DateTime(), nullable=False),
        sa.Column("createdAt", sa.DateTime(), nullable=True),
        sa.Column("updatedAt", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "groups",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_groups_created_by", "groups", ["created_by"], unique=False)
    op.create_index("idx_groups_name", "groups", ["name"], unique=False)
    op.create_table(
        "login_history",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("ip_address", sa.Text(), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("login_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_login_history_login_at", "login_history", ["login_at"], unique=False
    )
    op.create_index(
        "idx_login_history_user_id", "login_history", ["user_id"], unique=False
    )
    op.create_table(
        "user_preferences",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column(
            "default_models", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("default_temperature", sa.Float(), nullable=True),
        sa.Column("settings", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index(
        "idx_user_preferences_user_id", "user_preferences", ["user_id"], unique=False
    )
    op.create_table(
        "user_prompt_templates",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("entity_name", sa.Text(), nullable=False),
        sa.Column("prompt_content", sa.Text(), nullable=False),
        sa.Column("study_type", sa.Text(), nullable=True),
        sa.Column("system_prompt", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "name", "entity_name", name="uq_user_prompt_template"
        ),
    )
    op.create_index(
        "idx_user_prompt_templates_user_id",
        "user_prompt_templates",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "app_sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), nullable=True),
        sa.Column("last_step", sa.Text(), nullable=True),
        sa.Column(
            "configuration", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "evaluation_config", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "files_config", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("total_cost", sa.Float(), nullable=True),
        sa.Column("total_latency", sa.Float(), nullable=True),
        sa.Column("total_calls", sa.Integer(), nullable=True),
        sa.Column("shared_with_group_id", sa.UUID(), nullable=True),
        sa.Column("shared_by", sa.String(length=36), nullable=True),
        sa.Column("shared_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["shared_by"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["shared_with_group_id"], ["groups.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_app_sessions_shared_group",
        "app_sessions",
        ["shared_with_group_id"],
        unique=False,
        postgresql_where="shared_with_group_id IS NOT NULL",
    )
    op.create_index(
        "idx_app_sessions_updated_at", "app_sessions", ["updated_at"], unique=False
    )
    op.create_index(
        "idx_app_sessions_user_id", "app_sessions", ["user_id"], unique=False
    )
    op.create_table(
        "prompt_templates",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("study_type", sa.Text(), nullable=True),
        sa.Column("scope", sa.Text(), nullable=False),
        sa.Column("owner_user_id", sa.String(length=36), nullable=True),
        sa.Column("owner_group_id", sa.UUID(), nullable=True),
        sa.Column("system_prompt", sa.Text(), nullable=True),
        sa.Column("entities", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("summary_prompt", sa.Text(), nullable=True),
        sa.Column("variables", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("is_immutable", sa.Boolean(), nullable=True),
        sa.Column("tags", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("is_default", sa.Boolean(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=True),
        sa.Column("folder_id", sa.UUID(), nullable=True),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "scope IN ('user', 'group', 'global')", name="ck_templates_scope"
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(["owner_group_id"], ["groups.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["owner_user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_prompt_templates_created_by",
        "prompt_templates",
        ["created_by"],
        unique=False,
    )
    op.create_index(
        "idx_prompt_templates_owner_group",
        "prompt_templates",
        ["owner_group_id"],
        unique=False,
    )
    op.create_index(
        "idx_prompt_templates_owner_user",
        "prompt_templates",
        ["owner_user_id"],
        unique=False,
    )
    op.create_index(
        "idx_prompt_templates_scope", "prompt_templates", ["scope"], unique=False
    )
    op.create_index(
        "idx_prompt_templates_study_type",
        "prompt_templates",
        ["study_type"],
        unique=False,
    )
    op.create_table(
        "template_folders",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("scope", sa.Text(), nullable=False),
        sa.Column("owner_user_id", sa.String(length=36), nullable=True),
        sa.Column("owner_group_id", sa.UUID(), nullable=True),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "scope IN ('user', 'group', 'global')", name="ck_template_folders_scope"
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(["owner_group_id"], ["groups.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["owner_user_id"], ["user.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["template_folders.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_template_folders_owner_group",
        "template_folders",
        ["owner_group_id"],
        unique=False,
    )
    op.create_index(
        "idx_template_folders_owner_user",
        "template_folders",
        ["owner_user_id"],
        unique=False,
    )
    op.create_index(
        "idx_template_folders_parent", "template_folders", ["parent_id"], unique=False
    )
    op.create_index(
        "idx_template_folders_scope", "template_folders", ["scope"], unique=False
    )
    op.create_table(
        "user_groups",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("group_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.Text(), nullable=True),
        sa.Column("joined_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "role IN ('viewer', 'member', 'admin', 'owner')", name="ck_user_groups_role"
        ),
        sa.ForeignKeyConstraint(["group_id"], ["groups.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "group_id"),
    )
    op.create_index(
        "idx_user_groups_group_id", "user_groups", ["group_id"], unique=False
    )
    op.create_index("idx_user_groups_user_id", "user_groups", ["user_id"], unique=False)
    op.create_table(
        "documents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=True),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("file_hash", sa.Text(), nullable=False),
        sa.Column("filename", sa.Text(), nullable=False),
        sa.Column("file_path", sa.Text(), nullable=True),
        sa.Column("study_type", sa.Text(), nullable=True),
        sa.Column("processor_used", sa.Text(), nullable=True),
        sa.Column("processing_status", sa.Text(), nullable=True),
        sa.Column("processing_error", sa.Text(), nullable=True),
        sa.Column("extracted_text_path", sa.Text(), nullable=True),
        sa.Column("processed_at", sa.DateTime(), nullable=True),
        sa.Column("parse_cost", sa.Float(), nullable=True),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("parse_duration_seconds", sa.Float(), nullable=True),
        sa.Column("figure_count", sa.Integer(), nullable=True),
        sa.Column("table_count", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["session_id"], ["app_sessions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_documents_file_hash", "documents", ["file_hash"], unique=False)
    op.create_index(
        "idx_documents_session_id", "documents", ["session_id"], unique=False
    )
    op.create_index("idx_documents_user_id", "documents", ["user_id"], unique=False)
    op.create_table(
        "template_permissions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("template_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("can_read", sa.Boolean(), nullable=True),
        sa.Column("can_write", sa.Boolean(), nullable=True),
        sa.Column("granted_by", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["granted_by"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["template_id"], ["prompt_templates.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("template_id", "user_id", name="uq_template_permission"),
    )
    op.create_index(
        "idx_template_permissions_template",
        "template_permissions",
        ["template_id"],
        unique=False,
    )
    op.create_index(
        "idx_template_permissions_user",
        "template_permissions",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "template_versions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("template_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("system_prompt", sa.Text(), nullable=True),
        sa.Column("entities", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("summary_prompt", sa.Text(), nullable=True),
        sa.Column("variables", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("changed_by", sa.String(length=36), nullable=True),
        sa.Column("change_summary", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["changed_by"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["template_id"], ["prompt_templates.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("template_id", "version", name="uq_template_version"),
    )
    op.create_index(
        "idx_template_versions_template_id",
        "template_versions",
        ["template_id"],
        unique=False,
    )
    op.create_table(
        "extraction_results",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("entity_name", sa.Text(), nullable=False),
        sa.Column("model_id", sa.Text(), nullable=False),
        sa.Column("extracted_text", sa.Text(), nullable=True),
        sa.Column(
            "bbox_references", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("status", sa.Text(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("extracted_at", sa.DateTime(), nullable=True),
        sa.Column("prompt_tokens", sa.Integer(), nullable=True),
        sa.Column("completion_tokens", sa.Integer(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("cost", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["session_id"], ["app_sessions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "document_id",
            "entity_name",
            "model_id",
            name="uq_extraction_doc_entity_model",
        ),
    )
    op.create_index(
        "idx_extraction_results_document_id",
        "extraction_results",
        ["document_id"],
        unique=False,
    )
    op.create_index(
        "idx_extraction_results_entity_model",
        "extraction_results",
        ["entity_name", "model_id"],
        unique=False,
    )
    op.create_index(
        "idx_extraction_results_session_id",
        "extraction_results",
        ["session_id"],
        unique=False,
    )
    op.create_table(
        "evaluation_results",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("extraction_result_id", sa.UUID(), nullable=False),
        sa.Column("metric", sa.Text(), nullable=False),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("reasoning", sa.Text(), nullable=True),
        sa.Column("judge_model", sa.Text(), nullable=True),
        sa.Column("human_score", sa.Float(), nullable=True),
        sa.Column("ground_truth", sa.Text(), nullable=True),
        sa.Column("evaluation_cost", sa.Float(), nullable=True),
        sa.Column("evaluation_time", sa.Float(), nullable=True),
        sa.Column("evaluated_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["extraction_result_id"], ["extraction_results.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "extraction_result_id",
            "metric",
            "judge_model",
            name="uq_eval_extraction_metric_judge",
        ),
    )
    op.create_index(
        "idx_evaluation_results_extraction_id",
        "evaluation_results",
        ["extraction_result_id"],
        unique=False,
    )
    op.create_index(
        "idx_evaluation_results_judge",
        "evaluation_results",
        ["judge_model"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_evaluation_results_judge", table_name="evaluation_results")
    op.drop_index(
        "idx_evaluation_results_extraction_id", table_name="evaluation_results"
    )
    op.drop_table("evaluation_results")
    op.drop_index("idx_extraction_results_session_id", table_name="extraction_results")
    op.drop_index(
        "idx_extraction_results_entity_model", table_name="extraction_results"
    )
    op.drop_index("idx_extraction_results_document_id", table_name="extraction_results")
    op.drop_table("extraction_results")
    op.drop_index("idx_template_versions_template_id", table_name="template_versions")
    op.drop_table("template_versions")
    op.drop_index("idx_template_permissions_user", table_name="template_permissions")
    op.drop_index(
        "idx_template_permissions_template", table_name="template_permissions"
    )
    op.drop_table("template_permissions")
    op.drop_index("idx_documents_user_id", table_name="documents")
    op.drop_index("idx_documents_session_id", table_name="documents")
    op.drop_index("idx_documents_file_hash", table_name="documents")
    op.drop_table("documents")
    op.drop_index("idx_user_groups_user_id", table_name="user_groups")
    op.drop_index("idx_user_groups_group_id", table_name="user_groups")
    op.drop_table("user_groups")
    op.drop_index("idx_template_folders_scope", table_name="template_folders")
    op.drop_index("idx_template_folders_parent", table_name="template_folders")
    op.drop_index("idx_template_folders_owner_user", table_name="template_folders")
    op.drop_index("idx_template_folders_owner_group", table_name="template_folders")
    op.drop_table("template_folders")
    op.drop_index("idx_prompt_templates_study_type", table_name="prompt_templates")
    op.drop_index("idx_prompt_templates_scope", table_name="prompt_templates")
    op.drop_index("idx_prompt_templates_owner_user", table_name="prompt_templates")
    op.drop_index("idx_prompt_templates_owner_group", table_name="prompt_templates")
    op.drop_index("idx_prompt_templates_created_by", table_name="prompt_templates")
    op.drop_table("prompt_templates")
    op.drop_index("idx_app_sessions_user_id", table_name="app_sessions")
    op.drop_index("idx_app_sessions_updated_at", table_name="app_sessions")
    op.drop_index(
        "idx_app_sessions_shared_group",
        table_name="app_sessions",
        postgresql_where="shared_with_group_id IS NOT NULL",
    )
    op.drop_table("app_sessions")
    op.drop_index(
        "idx_user_prompt_templates_user_id", table_name="user_prompt_templates"
    )
    op.drop_table("user_prompt_templates")
    op.drop_index("idx_user_preferences_user_id", table_name="user_preferences")
    op.drop_table("user_preferences")
    op.drop_index("idx_login_history_user_id", table_name="login_history")
    op.drop_index("idx_login_history_login_at", table_name="login_history")
    op.drop_table("login_history")
    op.drop_index("idx_groups_name", table_name="groups")
    op.drop_index("idx_groups_created_by", table_name="groups")
    op.drop_table("groups")
    op.drop_table("verification")
    op.drop_table("user")
    op.drop_table("session")
    op.drop_table("account")
    # ### end Alembic commands ###
